server:
  port: 8020
### spring配置
spring:
  application:
    name: user
  profiles: dev #开发环境
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://localhost:3306/springclouddemo #数据库连接地址
    username: root
    password: root
    dbcp2:
      min-idle: 5  #数据库连接池的最小维持连接数
      initial-size: 5  #初始化连接数
      max-total: 5  #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间

### mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件路径
  type-aliases-package: cn.js.entities  #扫描实体类路径 生成别名
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  #mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka
    #向注册中心注册自己,默认为true
    register-with-eureka: true
    #去注册中心检索其他服务,用来调用
    fetch-registry: true
  #instance:
    #prefer-ip-address: true
    #instance-id: demo-user1-8020 #eureka服务地址别名配置

ribbon:
  ReadTimeout: 5000  #服建立连接后 最大的连接时间
  ConnectTimeout: 1000  #务连接超时时间

### 开启hystrix断路器  timeoutInMilliseconds
feign:
  hystrix:
    enabled: true
### hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000 #超时时间 缺省为1000
  threadpool:
    default:
      coreSize: 100
