server:
  port: 8040

spring:
  application:
    name: zuul
  profiles: dev #开发环境

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka

zuul:
  ignored-services: "*"
  routes:
    demouser.serviceId: user
    demouser.path: /user/**
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 5000