server:
  port: 8041

spring:
  application:
    name: zuul
  profiles: dev #开发环境

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka

zuul:
  routes:
    demouser: 
      serviceId: user
      path: /user/**
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  semaphore:
        max-semaphores: 200  #最高并发线程数

ribbon:
  ReadTimeout: 60000  #服建立连接后 最大的连接时间
  ConnectTimeout: 3000  #务连接超时时间


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #超时时间 缺省为1000
            
####开启所有服务端点刷新
management:
  endpoints:
    web:
      exposure:
        include: "*"
